version: "3.9"

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ./postgres-database:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123r
      - POSTGRES_USER=root
      - POSTGRES_DB=howur_db
